### PR TITLE
Fix Dockerfile merge changes.

### PR DESCRIPTION
**Pull request by iantei**

### CODE REVIEW

**Comment by iantei** [comment]
Testing changes:

Successful execution of `docker-compose -f docker-compose.dev.yml  up` command

<details><summary>Details</summary>
<p>

```
ashrest2-35384s:em-public-dashboard ashrest2$ docker-compose -f docker-compose.dev.yml up
[+] Running 3/3
 ✔ Container em-public-dashboard-db-1               Created                                                                                                                                                                                                                         0.0s 
 ✔ Container em-public-dashboard-notebook-server-1  Recreated                                                                                                                                                                                                                       0.2s 
 ✔ Container em-public-dashboard-dashboard-1        Recreated                                                                                                                                                                                                                       0.1s 
....  
em-public-dashboard-notebook-server-1  |     To access the notebook, open this file in a browser:
em-public-dashboard-notebook-server-1  |         file:///root/.local/share/jupyter/runtime/nbserver-19-open.html
em-public-dashboard-notebook-server-1  |     Or copy and paste one of these URLs:
em-public-dashboard-notebook-server-1  |         http://dae31421e6cf:8888/?token=a3b6e029bc618ee5ee6312f4c3df4744a8670a8833d30361
em-public-dashboard-notebook-server-1  |      or http://127.0.0.1:8888/?token=a3b6e029bc618ee5ee6312f4c3df4744a8670a8833d30361
```

</p>
</details>

**Review by Abby-Wheelis — APPROVED** [review]
This looks good, I was also seeing this error and these changes also resolved the error when I tried it out

**Comment by shankari** [comment]
Thanks @iantei for fixing this! I also realized this when I built the images over the weekend, but did not push them since it was already past midnight.

**Comment by shankari** [comment]
This is why we need automated testing for the public dashboard as well!

**Pull request merged**
