### PR TITLE
Hardcode program to default on both sides

### PR DESCRIPTION
**Pull request by zackAemmer**
https://github.com/e-mission/e-mission-docs/issues/788

### CODE REVIEW

**Review by shankari — CHANGES_REQUESTED** [review]
@zackAemmer You also need to change the crontab since that passes in the program to `generate_plots.py` 
- e.g. see 61e4386feb73bfba7513d8760fccf80a8610fd6c

**Comment by zackAemmer** [comment]
Frontend:

image

**Comment by shankari** [comment]
Can you search for "prepilot" in this directory and make sure that there are no further references? 

```
$ grep -r prepilot . | wc -l
```

currently (without merging your changes) gives me 35. You should get 0.

**Comment by zackAemmer** [comment]
I have 1 in vscode from a notebook we are no longer using:
image

Using grep:
image

I have 11 mentions with your grep command but I believe they are all files in .Trash-0

**Pull request merged**
