### PR TITLE
Add a graph for emission calculations

### PR DESCRIPTION
**Pull request by shankari**
- Add a new function (`CO2_emissions`) to scaffolding to calculate the CO2 emissions
- Add a new function (`CO2_impact`) to plots to plot it
- Enhance the energy calculation notebook to calculate the emissions and plot it

### CODE REVIEW

**Comment by shankari** [comment]
Testing done:
- Ran the notebook and generated the chart

**Comment by shankari** [comment]
@start0318 can you confirm that these are the only changes needed? I ran the notebook and it works. I will plan on merging this tomorrow morning

**Review by start0318 — APPROVED** [review]
It looks good Shankari.
I will make sure the variable names do not contain spaces. :) Next time.
I also expected a change in the name of the CO2 legend.

**Comment by shankari** [comment]
I don't think I changed any variable names, but I did swap the green and the red.

**Pull request merged**
